### ISSUE TITLE
This is beautifully documented

### ISSUE THREAD

**Issue by JosiahParry** [aethertap/leptos_axum_login#1]
🙏🏼 thank you! This is so beautifully documented!!! 

leptos is such a nascent framework and its docs are rather sparse (but much better than most other crates!) and things like this are a diamond in the rough. This is making it very clear how to use tower-sessions with leptos. 

Thank you so much <3

**Comment by aethertap** [comment]
Thanks for the kind words! I'm glad you're finding it useful. I'll have a 0.7 version up soon as well.
